version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sgt2023
      MYSQL_DATABASE: example
      MYSQL_USER: sgt
      MYSQL_PASSWORD: sgt2023
